[project]
name = "tts"
version = "1.0.0"
description = "The simple TTS service."
dependencies = [
    "flask",
    "flask-cors",
    "gunicorn"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
